force-app/main/default/objects/Fixed_Pricing1__c/fields/Rule_Id__c.field-meta.xml
<CustomField>
    <fullName>Rule_Id__c</fullName>
    <externalId>true</externalId>
    <label>Rule Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fixed_Pricing1__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved (Awaiting Publishing)</fullName>
            </value>
            <value>
                <fullName>Pending with Checker</fullName>
            </value>
            <value>
                <fullName>Checker Rejected</fullName>
            </value>
            <value>
                <fullName>Checker Approved</fullName>
            </value>
            <value>
                <fullName>Error (Override Required)</fullName>
            </value>
            <value>
                <fullName>Error (Override Not Required)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fixed_Pricing1__c/fields/Temp_Id__c.field-meta.xml
<CustomField>
    <fullName>Temp_Id__c</fullName>
    <label>Temp Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixedPricingTriggerHandler.cls
public class FixedPricingTriggerHandler {
    public static void beforeUpdateHandler(List<Fixed_Pricing1__c> triggeNew, Map<Id,Fixed_Pricing1__c> oldMap){
        for(Fixed_Pricing1__c fp : triggeNew){
            if(String.isNotBlank(fp.Status__c) && fp.Status__c != oldMap.get(fp.Id).Status__c && fp.Status__c == 'Error (Override Required)' && String.isBlank(fp.Rule_Id__c)){
                fp.Status__c = 'Error (Override Not Required)';
                fp.Temp_Id__c = NULL;
            }
        }
    }
}